#!/bin/bash

function usage() {
    if [[ "${1}" ]]; then
        echo "${1}"
    fi
    echo -n \
        "Usage: $(basename "$0") [api|postgres]
Follows logs for container.

Options:
(None) - Do nothing
api - Follow API logs
postgres - Follow postgres logs
"
}

SERVICE_NAME=''
while [[ $# -gt 0 ]]; do case $1 in
    api)
        SERVICE_NAME=api
        shift
        ;;
    postgres)
        SERVICE_NAME=postgres
        shift
        ;;
    --help)
        usage
        exit 0
        shift
        ;;
    *)
        shift
        ;;
esac done

if [[ -z "$SERVICE_NAME" ]]; then
    echo "Invalid argument"
    exit 1
fi
docker-compose logs -f $SERVICE_NAME